# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: adc40661265b7691186828e4e5bf539ca6b346509d75bf9f4acdf1fb2bff2d2370caca00e54faac183a25f8a756db04937f192373962af99c6ce92a123c17b75

test:
  secret_key_base: 3c854f4c6281fb7fbddfc325571d9d40d512e8ee0a69534e9672001ec2c387e72af0c29121bfe67c640a76f4bd9cd929b34097f543da62d4f5e0f3a8c28995d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
